apiVersion: v1
kind: ReplicationController
metadata:
  name: praneeth-rc
spec:
  replicas: 4
  selector:
    app: mynginx
  template:
    metadata:
      labels:
        app: mynginx
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80