apiVersion: v1
kind: ReplicationController
metadata:
  name: tomcat-rc
spec:
   replicas: 3
   template:
     metadata:
       labels:
         app: mytomcat
     spec:
       containers:
       - image: tomcat:8
         name: tomcat
         ports:
           - containerPort: 8080
